### ISSUE TITLE
SSL Cert Failed to verify

### ISSUE THREAD

**Issue by Trufaxx** [jackblk/DeviceAuthGenerator#3]
```
G:\DeviceAuthGenerator-main>generator.py
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\aiohttp\connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Python39\lib\asyncio\base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Python39\lib\asyncio\base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "C:\Python39\lib\asyncio\sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Python39\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Python39\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\DeviceAuthGenerator-main\generator.py", line 260, in <module>
    gen.run()
  File "G:\DeviceAuthGenerator-main\generator.py", line 255, in run
    loop.run_until_complete(self.start())
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "G:\DeviceAuthGenerator-main\generator.py", line 89, in start
    self.access_token = await self.get_access_token()
  File "G:\DeviceAuthGenerator-main\generator.py", line 134, in get_access_token
    async with self.http.request(
  File "C:\Python39\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Python39\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Python39\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Python39\lib\site-packages\aiohttp\connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Python39\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Python39\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Python39\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host account-public-service-prod.ol.epicgames.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)')]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021E37A24280>
```

I'm running into this problem with both the executable and the generator.py

**Comment by jackblk** [comment]
I don't have this issue. Do you run it behind a proxy? Looks like you're running it behind a HTTPS proxy, but the program is not written for this yet.
